// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlR6A1_JUGssZz2QaTsU6yn3GEZVjZELs',
    appId: '1:367392130289:web:b7ac0851e7bffcebf61550',
    messagingSenderId: '367392130289',
    projectId: 'hanbit-118ad',
    authDomain: 'hanbit-118ad.firebaseapp.com',
    storageBucket: 'hanbit-118ad.firebasestorage.app',
    measurementId: 'G-3WEBB9NT4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpsgJJzUB-xT_6r_4umQsZXdDOd3oSzE',
    appId: '1:367392130289:android:c938f9de6fcbfac3f61550',
    messagingSenderId: '367392130289',
    projectId: 'hanbit-118ad',
    storageBucket: 'hanbit-118ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_IifmtFdN_vZwucYpfXu5pCNQFM8GUI',
    appId: '1:367392130289:ios:52cad6c408079117f61550',
    messagingSenderId: '367392130289',
    projectId: 'hanbit-118ad',
    storageBucket: 'hanbit-118ad.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_IifmtFdN_vZwucYpfXu5pCNQFM8GUI',
    appId: '1:367392130289:ios:52cad6c408079117f61550',
    messagingSenderId: '367392130289',
    projectId: 'hanbit-118ad',
    storageBucket: 'hanbit-118ad.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlR6A1_JUGssZz2QaTsU6yn3GEZVjZELs',
    appId: '1:367392130289:web:ff3445565a4605a8f61550',
    messagingSenderId: '367392130289',
    projectId: 'hanbit-118ad',
    authDomain: 'hanbit-118ad.firebaseapp.com',
    storageBucket: 'hanbit-118ad.firebasestorage.app',
    measurementId: 'G-J6Z4QEK2XT',
  );
}
